# Use the latest version of Ubuntu as the base image
FROM ubuntu:latest

# Update APT package list
RUN apt-get update

# Upgrade installed packages
RUN apt-get upgrade -y

# Command to run when the container starts
CMD echo "Hello, World!"
